sudo: false

arch:
  - amd64
  - ppc64le

language: node_js

node_js:
  - "0.10"
  - "0.12"
  - "14"
  - "15"
  - "stable"

jobs:
  exclude:
     - node_js: "0.10"
       arch: ppc64le
     - node_js: "0.12"
       arch: ppc64le

script:
  - npm run lint
  - npm test
  - npm run coverage
