sudo: false

arch:
  - amd64
  - ppc64le

language: node_js

node_js:
  - "0.10"
  - "0.12"
  - "4"
  - "6"
  - "8"
  - "10"
  - "12"

jobs:
  exclude:
     - node_js: "0.10"
       arch: ppc64le
     - node_js: "0.12"
       arch: ppc64le

script:
  - npm run lint
  - npm test
  - npm run coverage
